---
title: "Hard intervall"
author: "Simen Løkken"
format: html
editor: visual
---

### Tema

Her ligger all koden fra dataanalysen til den tredje økta, dvs. den harde intervallen både kaldt og varmt.

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```

#### **Last inn pakker og tema**

```{r}

library(tidyverse)
library(ggtext)
library(patchwork)

theme_set(theme_bw())
```

```{r}

setwd("C:/Users/simen/Desktop/hvgs_des_2023/data")

hard_intervall <- read_csv("hard_intervall.csv")
```

#### **Datarydding**

Disse dataene er ryddet for dere.

#### **Plott**

Watt, puls og kadens som en funksjon av tid.

```{r}

# Puls som funksjon av tid

p1 <- hard_intervall |> 
  ggplot(aes(x = time, y = heartrate)) +
  geom_line(color = "red", alpha = 0.8) +
  scale_x_continuous(name = NULL) + 
  scale_y_continuous(name = "Puls (slag/min)") +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(size = 10),
    plot.subtitle = element_markdown(size = 8),
    axis.title = element_text(size = 10),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  )

p1

# Watt som en funksjon av tid

p2 <- hard_intervall |> 
  filter(watts < 260 & watts > 125) |> 
  ggplot(aes(x = time, y = watts)) +
  geom_line() +
  scale_x_continuous(name = NULL) + 
  scale_y_continuous(
    name = "Watt (W)",
    breaks = seq(130, 260, 30)
    ) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(size = 10),
    plot.subtitle = element_markdown(size = 8),
    axis.title = element_text(size = 10),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  )

p2

# Kadens som en funksjon av tid

p3 <- hard_intervall |> 
  ggplot(aes(x = time, y = cadence)) +
  geom_line() +
  scale_x_continuous(name = "Tid (sekunder)") + 
  scale_y_continuous(name = "Kadens (RPM)") +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title = element_text(size = 10),
    plot.subtitle = element_markdown(size = 8),
    axis.title = element_text(size = 10),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  )

p3

hard_int_puls_watt <- p1 / p2

hard_int_puls_watt_kadens <- p1 / p2 / p3
```

```{r}

# Lagre plott

setwd("C:/Users/simen/Desktop/hvgs_des_2023/grafer")

ggsave(hard_int_puls_watt,
       filename = "hard_int_puls_watt.jpg",
       dpi = 300,
       height = 4,
       width = 7)

ggsave(hard_int_puls_watt_kadens,
       filename = "hard_int_puls_watt_kadens.jpg",
       dpi = 300,
       height = 4,
       width = 7)
```

```{r}

# Gjør intervall kategorisk

hard_intervall <- hard_intervall |> 
  mutate(interval = as.factor(interval))

library(introdataviz)

# Fiolinplott av puls for hele int.drag

p5 <- hard_intervall |> 
  filter(interval != 0) |> 
  ggplot(aes(
    x = interval, 
    y = heartrate, 
    fill = factor(interval))
    ) +
  geom_violin(alpha = 0.8, show.legend = F, fill = "royalblue") +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  ) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Puls (slag/min)") +
  theme(
    plot.title = element_text(size = 10),
    plot.subtitle = element_markdown(size = 8),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  ) +
  labs(title = "Pulsfordeling for alle intervalldragene")

p5

# Fiolinplott av puls for siste tre minutt av int.drag

p6 <- hard_intervall |> 
  group_by(interval) |> 
  slice_tail(n = 180) |> 
  filter(interval != 0) |> 
  ggplot(aes(x = interval, y = heartrate)) +
  geom_violin(alpha = 0.8, fill = "royalblue") +
   theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  ) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Puls (slag/min)") +
  theme(
    plot.title = element_text(size = 10),
    plot.subtitle = element_markdown(size = 8),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  ) +
  labs(
    title = "Pulsfordeling for alle intervalldragene",
    subtitle = "Filtrert siste tre minuttene"
  )

p6

p5_p6 <- p5 / p6
```

```{r}

# Lagre plott

setwd("C:/Users/simen/Desktop/hvgs_des_2023/grafer")

ggsave(p5, filename = "hard_int_puls_fiolin.jpg",
       dpi = 300,
       height = 5,
       width = 8)

ggsave(p6, filename = "hard_int_puls_fiolin_siste_tre_min.jpg",
       dpi = 300,
       height = 5,
       width = 8)

ggsave(p5_p6, filename = "hard_int_puls_fiolin_kombinert.jpg",
       dpi = 300,
       height = 5,
       width = 8)
```
