---
title: "Terskelintervall"
format: html
editor: visual
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```

```{r}

library(tidyverse)
library(ggtext)
library(patchwork)


theme_set(theme_bw())
```

#### Last inn data

```{r}

setwd("C:/Users/simen/Desktop/hvgs_des_2023/data")

terskelintervall_kald_varm <- read_csv("terskelintervall_kald_varm.csv")
```

#### Rydd data

Disse dataene er ryddet for dere, men vi filtrerer ut de kolonnene vi er interessert i og gjør intervalkolonna til en kategorisk variablel (for å kunne plotte et fiolinplott).

```{r}

terskelintervall_kald_varm <- terskelintervall_kald_varm |> 
  select(time, heartrate, watts, interval, temperature) |> 
  mutate(interval = as.factor(interval))
```

#### Plott

Fiolinplott for pulsfordeling for hvert intervalldrag, kald og varm økt.

```{r}

library(introdataviz)

# Puls

p3 <- terskelintervall_kald_varm |> 
  drop_na() |> 
  ggplot(aes(interval, heartrate, fill = temperature)) +
  geom_split_violin(alpha = 0.8, show.legend = F) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()
  ) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Puls (slag/min)") +
  labs(
    title = "Pulsfordeling for hvert intervalldrag",
    subtitle = paste("<span style='color:#3caae6'>Kald økt</span>", "og",
    "<span style='color:#ed4e4e'>varm økt</span>")
    ) +
  theme(
    plot.title = element_text(size = 10),
    plot.subtitle = element_markdown(size = 8),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  ) +
 scale_fill_manual(values = c("#3caae6", "#ed4e4e"))

p3
```

```{r}

# Lagre plott

setwd("C:/Users/simen/Desktop/hvgs_des_2023/grafer")

ggsave(plot = p3,
       filename = "terskel_pulsfordeling_intervalldrag.jpg",
       dpi = 300,
       height = 4,
       width = 7
)
```

Fiolinplott filtrert etter to minutter ut i dragene.

```{r}

p3 <- terskelintervall_kald_varm |> 
  filter()
  drop_na() |> 
  ggplot(aes(interval, heartrate, fill = temperature)) +
  geom_split_violin(alpha = 0.8, show.legend = F) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()
  ) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Puls (slag/min)") +
  labs(
    title = "Pulsfordeling for hvert intervalldrag",
    subtitle = paste("<span style='color:#3caae6'>Kald økt</span>", "og",
    "<span style='color:#ed4e4e'>varm økt</span>")
    ) +
  theme(
    plot.title = element_text(size = 10),
    plot.subtitle = element_markdown(size = 8),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  ) +
 scale_fill_manual(values = c("#3caae6", "#ed4e4e"))

p3

```

```{r}

p5 <- terskelintervall_kald_varm |> 
  filter(heartrate > 100) |> 
  filter(time < 2950) |> 
  ggplot(aes(x = time, y = heartrate)) +
  geom_line(aes(color = temperature), show.legend = F, alpha = 0.8) +
  scale_x_continuous(name = "Tid (sekunder)") +
  scale_y_continuous(
    name = "Puls (slag/min)",
    breaks = seq(100, 180, 20)
  ) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  ) + 
  scale_color_manual(
    name = "Temperatur",
    values = c("#3caae6", "#ed4e4e"),
    labels = c("Kald", "Varm")
    ) +
  theme(
    plot.title = element_text(size = 10),
    plot.subtitle = element_text(size = 8),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  )
  

library(introdataviz)

p6 <- terskelintervall_kald_varm |> 
  drop_na() |> 
  ggplot(aes(interval, heartrate, fill = temperature)) +
  geom_split_violin(alpha = 0.8, show.legend = F) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank()
  ) +
  scale_x_discrete(name = "Intervalldrag") +
  scale_y_continuous(name = "Puls (slag/min)") +
  theme(
    plot.title = element_text(size = 10),
    plot.subtitle = element_markdown(size = 8),
    axis.title.x = element_text(size = 8),
    axis.title.y = element_text(size = 8)
  ) +
 scale_fill_manual(values = c("#3caae6", "#ed4e4e"))

terskel_puls_watt_tid_split <- p5 + p6 + plot_layout(ncol = 1)
```

```{r}

# Lagre plott

setwd("C:/Users/simen/Desktop/hvgs_des_2023/grafer")

ggsave(plot = terskel_puls_watt_tid_split,
       filename = "terskel_puls_watt_tid_og_puls_splitt.jpg",
       dpi = 300,
       height = 4,
       width = 8
)
```
